/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dotcontrolltec;

import com.fasterxml.jackson.databind.ser.std.StdKeySerializers;
import com.mycompany.dotcontrolltec.computadores.Cpu;
import com.mycompany.dotcontrolltec.computadores.Disco;
import com.mycompany.dotcontrolltec.computadores.Grafico;
import com.mycompany.dotcontrolltec.computadores.InformacoesSistema;
import com.mycompany.dotcontrolltec.computadores.Ram;
import com.mycompany.exemplo.bd.Computador;
import com.mycompany.exemplo.bd.Conection;
import com.mycompany.exemplo.bd.Tecnico;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JPanel;

import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import oshi.SystemInfo;
import oshi.software.os.OSProcess;

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Integer contador = 0;
    Integer contador2 = 0;
    Double usoCpu;
    Integer fkComputador = 0;

    Cpu cpu = new Cpu();
    Ram ram = new Ram();
    Disco disco = new Disco();
    Grafico grafico = new Grafico();
    SystemInfo si = new SystemInfo();
    Conection config = new Conection();
    JdbcTemplate con = new JdbcTemplate(config.getDatasource());
    InformacoesSistema infosis = new InformacoesSistema();
    
    DefaultCategoryDataset dadosCpu = new DefaultCategoryDataset();
    DefaultPieDataset dadosRam = new DefaultPieDataset();
    DefaultPieDataset dadosDisco = new DefaultPieDataset();
    //loops temporizadores
    Timer timerCpu;
    private final Tecnico tecnico;

    /**
     * Creates new form TelaPrincipal
     * @param tecnico
     */
    public TelaPrincipal(Tecnico tecnico) {
        this.timerCpu = new Timer(1000, acaoRam);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.tecnico = tecnico;
               

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jpMenu = new javax.swing.JPanel();
        jpMenuCpu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpMenuRam = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpMenuInformacoes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpMenuDisco = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jpMenuProcessos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpTela = new javax.swing.JPanel();
        jpTelaInicio = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpTelaProcessos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcesses = new javax.swing.JTable();
        jpTelaInformacoes = new javax.swing.JPanel();
        jpTelaRam = new javax.swing.JPanel();
        jpGraficoRam = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblRamEmUso = new javax.swing.JLabel();
        lblRamLivre = new javax.swing.JLabel();
        lblRamEspacoTotal = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblRamTipoMemoria = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblRamPorcentagem1 = new javax.swing.JLabel();
        jpTelaDisco = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jpGraficoDisco = new javax.swing.JPanel();
        lblDiscoEspacoTotal = new javax.swing.JLabel();
        lblDiscoLivre = new javax.swing.JLabel();
        lblDiscoUso = new javax.swing.JLabel();
        jpTelaCpu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFrequenciaMaxima = new javax.swing.JLabel();
        lblFrequenciaAtual = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblQtdProcessos = new javax.swing.JLabel();
        jpGraficoCpu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUsoCpu = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTemperaturaCpu = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblCpuBits = new javax.swing.JLabel();
        lblCpuNome = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jpMenuCpu.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuCpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuCpuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CPU");

        javax.swing.GroupLayout jpMenuCpuLayout = new javax.swing.GroupLayout(jpMenuCpu);
        jpMenuCpu.setLayout(jpMenuCpuLayout);
        jpMenuCpuLayout.setHorizontalGroup(
            jpMenuCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuCpuLayout.setVerticalGroup(
            jpMenuCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jpMenuRam.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuRam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuRamMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RAM");

        javax.swing.GroupLayout jpMenuRamLayout = new javax.swing.GroupLayout(jpMenuRam);
        jpMenuRam.setLayout(jpMenuRamLayout);
        jpMenuRamLayout.setHorizontalGroup(
            jpMenuRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuRamLayout.setVerticalGroup(
            jpMenuRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jpMenuInformacoes.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuInformacoesMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Informações do sistema");

        javax.swing.GroupLayout jpMenuInformacoesLayout = new javax.swing.GroupLayout(jpMenuInformacoes);
        jpMenuInformacoes.setLayout(jpMenuInformacoesLayout);
        jpMenuInformacoesLayout.setHorizontalGroup(
            jpMenuInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuInformacoesLayout.setVerticalGroup(
            jpMenuInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jpMenuDisco.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuDisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuDiscoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DISCO");

        javax.swing.GroupLayout jpMenuDiscoLayout = new javax.swing.GroupLayout(jpMenuDisco);
        jpMenuDisco.setLayout(jpMenuDiscoLayout);
        jpMenuDiscoLayout.setHorizontalGroup(
            jpMenuDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuDiscoLayout.setVerticalGroup(
            jpMenuDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText(".ControlTec");

        jPanel6.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jpMenuProcessos.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuProcessos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuProcessosMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PROCESSOS");

        javax.swing.GroupLayout jpMenuProcessosLayout = new javax.swing.GroupLayout(jpMenuProcessos);
        jpMenuProcessos.setLayout(jpMenuProcessosLayout);
        jpMenuProcessosLayout.setHorizontalGroup(
            jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
            .addGroup(jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        );
        jpMenuProcessosLayout.setVerticalGroup(
            jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
            .addGroup(jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenuCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuDisco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
            .addComponent(jpMenuProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpMenuCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpTela.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Bem Vindo!");

        javax.swing.GroupLayout jpTelaInicioLayout = new javax.swing.GroupLayout(jpTelaInicio);
        jpTelaInicio.setLayout(jpTelaInicioLayout);
        jpTelaInicioLayout.setHorizontalGroup(
            jpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaInicioLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(163, 163, 163))
        );
        jpTelaInicioLayout.setVerticalGroup(
            jpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaInicioLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel14)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jpTelaProcessos.setBackground(new java.awt.Color(255, 255, 255));

        tblProcesses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPU", "Memory"
            }
        ));
        jScrollPane1.setViewportView(tblProcesses);

        javax.swing.GroupLayout jpTelaProcessosLayout = new javax.swing.GroupLayout(jpTelaProcessos);
        jpTelaProcessos.setLayout(jpTelaProcessosLayout);
        jpTelaProcessosLayout.setHorizontalGroup(
            jpTelaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        jpTelaProcessosLayout.setVerticalGroup(
            jpTelaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        jpTelaInformacoes.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpTelaInformacoesLayout = new javax.swing.GroupLayout(jpTelaInformacoes);
        jpTelaInformacoes.setLayout(jpTelaInformacoesLayout);
        jpTelaInformacoesLayout.setHorizontalGroup(
            jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jpTelaInformacoesLayout.setVerticalGroup(
            jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jpTelaRam.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpGraficoRamLayout = new javax.swing.GroupLayout(jpGraficoRam);
        jpGraficoRam.setLayout(jpGraficoRamLayout);
        jpGraficoRamLayout.setHorizontalGroup(
            jpGraficoRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jpGraficoRamLayout.setVerticalGroup(
            jpGraficoRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Ram");

        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Espaço livre:");

        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Em uso:");

        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("% de uso");

        lblRamEmUso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRamEmUso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRamEmUso.setText("0,00GB");

        lblRamLivre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRamLivre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRamLivre.setText("0,00GB");

        lblRamEspacoTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRamEspacoTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRamEspacoTotal.setText("0,0GB");

        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Tipo:");

        lblRamTipoMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRamTipoMemoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRamTipoMemoria.setText("...");

        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("Espeaço total:");

        lblRamPorcentagem1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRamPorcentagem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRamPorcentagem1.setText("0,0%");

        javax.swing.GroupLayout jpTelaRamLayout = new javax.swing.GroupLayout(jpTelaRam);
        jpTelaRam.setLayout(jpTelaRamLayout);
        jpTelaRamLayout.setHorizontalGroup(
            jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaRamLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(19, 19, 19))
            .addGroup(jpTelaRamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRamTipoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpTelaRamLayout.createSequentialGroup()
                        .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRamLivre)
                            .addComponent(jLabel17)
                            .addComponent(jLabel24))
                        .addGap(51, 51, 51)
                        .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(lblRamEmUso))
                        .addGap(71, 71, 71)
                        .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(lblRamPorcentagem1))
                        .addGap(57, 57, 57)
                        .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRamEspacoTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpGraficoRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTelaRamLayout.setVerticalGroup(
            jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaRamLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jpGraficoRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRamEmUso)
                    .addComponent(lblRamLivre)
                    .addComponent(lblRamPorcentagem1)
                    .addComponent(lblRamEspacoTotal))
                .addGap(34, 34, 34)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRamTipoMemoria)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jpTelaDisco.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Disco");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Espaço total");

        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("em uso:");

        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Espaço Livre");

        javax.swing.GroupLayout jpGraficoDiscoLayout = new javax.swing.GroupLayout(jpGraficoDisco);
        jpGraficoDisco.setLayout(jpGraficoDiscoLayout);
        jpGraficoDiscoLayout.setHorizontalGroup(
            jpGraficoDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        jpGraficoDiscoLayout.setVerticalGroup(
            jpGraficoDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        lblDiscoEspacoTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiscoEspacoTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiscoEspacoTotal.setText("0,0GB");

        lblDiscoLivre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiscoLivre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiscoLivre.setText("0,0GB");

        lblDiscoUso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiscoUso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiscoUso.setText("0,0GB");

        javax.swing.GroupLayout jpTelaDiscoLayout = new javax.swing.GroupLayout(jpTelaDisco);
        jpTelaDisco.setLayout(jpTelaDiscoLayout);
        jpTelaDiscoLayout.setHorizontalGroup(
            jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaDiscoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaDiscoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpGraficoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpTelaDiscoLayout.createSequentialGroup()
                        .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(lblDiscoEspacoTotal))
                        .addGap(130, 130, 130)
                        .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(lblDiscoLivre))
                        .addGap(92, 92, 92)
                        .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDiscoUso)
                            .addComponent(jLabel22))))
                .addGap(63, 63, 63))
        );
        jpTelaDiscoLayout.setVerticalGroup(
            jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGraficoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscoEspacoTotal)
                    .addComponent(lblDiscoLivre)
                    .addComponent(lblDiscoUso))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jpTelaCpu.setBackground(new java.awt.Color(255, 255, 255));
        jpTelaCpu.setInheritsPopupMenu(true);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Frequencia Maxima:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Frequencia atual:");

        lblFrequenciaMaxima.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFrequenciaMaxima.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrequenciaMaxima.setText("0.0 GHz");

        lblFrequenciaAtual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFrequenciaAtual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrequenciaAtual.setText("0.0 GHz");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Quantidade de processos:");

        lblQtdProcessos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQtdProcessos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQtdProcessos.setText("0");

        javax.swing.GroupLayout jpGraficoCpuLayout = new javax.swing.GroupLayout(jpGraficoCpu);
        jpGraficoCpu.setLayout(jpGraficoCpuLayout);
        jpGraficoCpuLayout.setHorizontalGroup(
            jpGraficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        jpGraficoCpuLayout.setVerticalGroup(
            jpGraficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("% de ultilização");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Utilização:");

        lblUsoCpu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsoCpu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsoCpu.setText("0%");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("CPU");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Temperatura:");

        lblTemperaturaCpu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTemperaturaCpu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTemperaturaCpu.setText("0.0°C");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Suporta 64 bit?");

        lblCpuBits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCpuBits.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCpuBits.setText("...");

        lblCpuNome.setBackground(new java.awt.Color(255, 255, 255));
        lblCpuNome.setForeground(new java.awt.Color(153, 153, 153));
        lblCpuNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpuNome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jpTelaCpuLayout = new javax.swing.GroupLayout(jpTelaCpu);
        jpTelaCpu.setLayout(jpTelaCpuLayout);
        jpTelaCpuLayout.setHorizontalGroup(
            jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTelaCpuLayout.createSequentialGroup()
                        .addComponent(jpGraficoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jpTelaCpuLayout.createSequentialGroup()
                        .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpTelaCpuLayout.createSequentialGroup()
                                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(lblFrequenciaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(lblUsoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFrequenciaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(lblQtdProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpuBits, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(lblTemperaturaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCpuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        jpTelaCpuLayout.setVerticalGroup(
            jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(lblCpuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGraficoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrequenciaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrequenciaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperaturaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpuBits, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jpTelaLayout = new javax.swing.GroupLayout(jpTela);
        jpTela.setLayout(jpTelaLayout);
        jpTelaLayout.setHorizontalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTelaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaRam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTelaLayout.setVerticalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTelaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpMenuCpuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuCpuMouseClicked
        trocaCor(jpMenuCpu, jpMenuRam, jpMenuDisco, jpMenuInformacoes, jpMenuProcessos);
        trocaAba(jpTelaCpu, jpTelaRam, jpTelaDisco, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);

    }//GEN-LAST:event_jpMenuCpuMouseClicked

    private void jpMenuRamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuRamMouseClicked
        trocaCor(jpMenuRam, jpMenuDisco, jpMenuCpu, jpMenuInformacoes, jpMenuProcessos);
        trocaAba(jpTelaRam, jpTelaCpu, jpTelaDisco, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);


    }//GEN-LAST:event_jpMenuRamMouseClicked

    private void jpMenuDiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuDiscoMouseClicked
        trocaCor(jpMenuDisco, jpMenuCpu, jpMenuInformacoes, jpMenuProcessos, jpMenuRam);
        trocaAba(jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);
    }//GEN-LAST:event_jpMenuDiscoMouseClicked

    private void jpMenuInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuInformacoesMouseClicked
        // TODO add your handling code here:
        trocaCor(jpMenuInformacoes, jpMenuDisco, jpMenuCpu, jpMenuProcessos, jpMenuRam);
        trocaAba(jpTelaInformacoes, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaProcessos, jpTelaInicio);
    }//GEN-LAST:event_jpMenuInformacoesMouseClicked

    private void jpMenuProcessosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuProcessosMouseClicked
        // TODO add your handling code here:
        trocaCor(jpMenuProcessos, jpMenuInformacoes, jpMenuDisco, jpMenuCpu, jpMenuRam);
        trocaAba(jpTelaProcessos, jpTelaInformacoes, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInicio);
    }//GEN-LAST:event_jpMenuProcessosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Quando o jframe abre
        trocaAba(jpTelaInicio, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInformacoes, jpTelaProcessos);
        String select = "select * from Computador where serialnum = ?;";
        List<Computador> dadosComp = con.query(select,new BeanPropertyRowMapper(Computador.class),infosis.serialNumber());
        
  
        
        for(Computador c : dadosComp){
            fkComputador = c.getIdComputador();
        };
        
        ActionListener acao = (ActionEvent executar) -> {
            //tela CPU
            exibeDadosCpu();
            //tela RAM
            exibeDadosRam();
            //tela processos
            exibeProcessos();
            //tela disco
            exibeDisco();
            //inserindo os dados
        

        };
        Timer tempo = new Timer(1000, acao);

        //iniciar o temporizador
        tempo.start();

    }//GEN-LAST:event_formWindowOpened
    ActionListener acaoRam = ((arg0) -> {
        exibeDadosRam();
    });
    /**
     * @param args the command line arguments
     */


    public void trocaCor(JPanel troca, JPanel mantem1, JPanel mantem2, JPanel mantem3, JPanel mantem4) {
        troca.setBackground(new Color(51, 51, 255));
        mantem1.setBackground(new Color(204, 204, 255));
        mantem2.setBackground(new Color(204, 204, 255));
        mantem3.setBackground(new Color(204, 204, 255));
        mantem4.setBackground(new Color(204, 204, 255));
    }

    public void trocaAba(JPanel exibe, JPanel oculta1, JPanel oculta2, JPanel oculta3, JPanel oculta4, JPanel oculta5) {
        exibe.setVisible(true);
        oculta1.setVisible(false);
        oculta2.setVisible(false);
        oculta3.setVisible(false);
        oculta4.setVisible(false);
        oculta5.setVisible(false);

    }

    private void exibeDadosCpu() {

        usoCpu = cpu.porcetagemDeUso();
        lblFrequenciaAtual.setText(String.format("%.2f GHz", cpu.frenquenciaCpu()));
        lblFrequenciaMaxima.setText(String.format("%.2f GHz", cpu.frequenciaMax()));
        lblQtdProcessos.setText(cpu.quantidadeProcessos().toString());
        lblUsoCpu.setText(String.format("%.2f%%", usoCpu));
        lblTemperaturaCpu.setText(String.format("%.2f°C", cpu.Temperatura()));
        lblCpuBits.setText(cpu.bits());
        lblCpuNome.setText(cpu.nome());

        dadosCpu.addValue(usoCpu, "Uso da cpu", LocalTime.now());
        contador++;
        if (contador.equals(6)) {
            dadosCpu.removeColumn(0);
            contador--;

        }
        grafico.GraficoLinha(dadosCpu, "CPU", "% de uso", "Hora", jpGraficoCpu);
        con.update("insert into UsoAtual values(?,?,'CPU',?)", usoCpu,LocalDateTime.now() , fkComputador);
        
        

    }

    private void exibeDadosRam() {
        lblRamEmUso.setText(String.format("%.2fGB", ram.qtdMemoriaRamUsada()));
        lblRamLivre.setText(String.format("%.2fGB", ram.qtdMemoriaRamLivre()));
        lblRamEspacoTotal.setText(String.format("%.2fGB", ram.qtdMemoriaRamTotal()));
        lblRamPorcentagem1.setText(String.format("%.1f%%", ram.porcetagemDeMemoria()));
        lblRamTipoMemoria.setText(ram.tipoMemoria());
        
        Double usoRam = ram.qtdMemoriaRamUsada();
        Double espacoLivre = ram.qtdMemoriaRamLivre();
        dadosRam.setValue("em uso", usoRam);
        dadosRam.setValue("livre", espacoLivre);
        
        grafico.GraficoDunuts(dadosRam, "Ram", jpGraficoRam);
        con.update("insert into UsoAtual values(?,?,'RAM',?)", ram.porcetagemDeMemoria(),LocalDateTime.now() , fkComputador);

    }
    public void exibeDisco(){
        lblDiscoEspacoTotal.setText(String.format("%.2fGB", disco.qtdEspacoTotalDisco()));
        lblDiscoLivre.setText(String.format("%.2fGB", disco.qtdEspacoLivre()));
        lblDiscoUso.setText(String.format("%.2fGB", disco.qtdEspacoUsadoDisco()));
        
        dadosDisco.setValue("em uso", disco.qtdEspacoUsadoDisco());
        dadosDisco.setValue("Livre", disco.qtdEspacoLivre());
        grafico.GraficoDunuts(dadosDisco, "uso disco", jpGraficoDisco);
        
         con.update("insert into UsoAtual values(?,?,'DISCO',?)", disco.porcetagemDisco(),LocalDateTime.now() , fkComputador);
        
    }

    public void exibeProcessos() {
         DefaultTableModel model = (DefaultTableModel) tblProcesses.getModel();

        Integer cpuCount = si.getHardware().getProcessor().getLogicalProcessorCount();
        Long totalMem = si.getHardware().getMemory().getTotal();
        model.setRowCount(0);

        for (OSProcess process : si.getOperatingSystem().getProcesses()) {

            if (process.getProcessID() > 0) {
                model.addRow(new Object[]{
                    process.getProcessID(),
                    process.getName(),
                    String.format("%.1f%%", 100.0 * process.getProcessCpuLoadCumulative() / cpuCount),
                    String.format("%.1f%%", 100.0 * process.getResidentSetSize() / totalMem)
                });

            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpGraficoCpu;
    private javax.swing.JPanel jpGraficoDisco;
    private javax.swing.JPanel jpGraficoRam;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpMenuCpu;
    private javax.swing.JPanel jpMenuDisco;
    private javax.swing.JPanel jpMenuInformacoes;
    private javax.swing.JPanel jpMenuProcessos;
    private javax.swing.JPanel jpMenuRam;
    private javax.swing.JPanel jpTela;
    private javax.swing.JPanel jpTelaCpu;
    private javax.swing.JPanel jpTelaDisco;
    private javax.swing.JPanel jpTelaInformacoes;
    private javax.swing.JPanel jpTelaInicio;
    private javax.swing.JPanel jpTelaProcessos;
    private javax.swing.JPanel jpTelaRam;
    private javax.swing.JLabel lblCpuBits;
    private javax.swing.JLabel lblCpuNome;
    private javax.swing.JLabel lblDiscoEspacoTotal;
    private javax.swing.JLabel lblDiscoLivre;
    private javax.swing.JLabel lblDiscoUso;
    private javax.swing.JLabel lblFrequenciaAtual;
    private javax.swing.JLabel lblFrequenciaMaxima;
    private javax.swing.JLabel lblQtdProcessos;
    private javax.swing.JLabel lblRamEmUso;
    private javax.swing.JLabel lblRamEspacoTotal;
    private javax.swing.JLabel lblRamLivre;
    private javax.swing.JLabel lblRamPorcentagem1;
    private javax.swing.JLabel lblRamTipoMemoria;
    private javax.swing.JLabel lblTemperaturaCpu;
    private javax.swing.JLabel lblUsoCpu;
    private javax.swing.JTable tblProcesses;
    // End of variables declaration//GEN-END:variables
}
