/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dotcontrolltec;

import com.mycompany.dotcontrolltec.computadores.Cpu;
import com.mycompany.dotcontrolltec.computadores.Grafico;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import javax.swing.JPanel;

import javax.swing.Timer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Integer contador = 0;
    Double usoCpu;

    Cpu cpu = new Cpu();
    Grafico graficoCpu = new Grafico("grafico cpu");
     DefaultCategoryDataset dados = new DefaultCategoryDataset();
    

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jpMenu = new javax.swing.JPanel();
        jpMenuCpu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpMenuRam = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpMenuInformacoes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpMenuDisco = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jpMenuProcessos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpTela = new javax.swing.JPanel();
        jpTelaInicio = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpTelaProcessos = new javax.swing.JPanel();
        jpTelaInformacoes = new javax.swing.JPanel();
        jpTelaRam = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpTelaDisco = new javax.swing.JPanel();
        jpTelaCpu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFrequenciaMaxima = new javax.swing.JLabel();
        lblFrequenciaAtual = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblQtdProcessos = new javax.swing.JLabel();
        jpGraficoCpu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUsoCpu = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTemperaturaCpu = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jpMenuCpu.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuCpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuCpuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CPU");

        javax.swing.GroupLayout jpMenuCpuLayout = new javax.swing.GroupLayout(jpMenuCpu);
        jpMenuCpu.setLayout(jpMenuCpuLayout);
        jpMenuCpuLayout.setHorizontalGroup(
            jpMenuCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuCpuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(101, 101, 101))
        );
        jpMenuCpuLayout.setVerticalGroup(
            jpMenuCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuCpuLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jpMenuRam.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuRam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuRamMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("RAM");

        javax.swing.GroupLayout jpMenuRamLayout = new javax.swing.GroupLayout(jpMenuRam);
        jpMenuRam.setLayout(jpMenuRamLayout);
        jpMenuRamLayout.setHorizontalGroup(
            jpMenuRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuRamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(102, 102, 102))
        );
        jpMenuRamLayout.setVerticalGroup(
            jpMenuRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuRamLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jpMenuInformacoes.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuInformacoesMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Informações do sistema");

        javax.swing.GroupLayout jpMenuInformacoesLayout = new javax.swing.GroupLayout(jpMenuInformacoes);
        jpMenuInformacoes.setLayout(jpMenuInformacoesLayout);
        jpMenuInformacoesLayout.setHorizontalGroup(
            jpMenuInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuInformacoesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenuInformacoesLayout.setVerticalGroup(
            jpMenuInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jpMenuDisco.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuDisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuDiscoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("DISCO");

        javax.swing.GroupLayout jpMenuDiscoLayout = new javax.swing.GroupLayout(jpMenuDisco);
        jpMenuDisco.setLayout(jpMenuDiscoLayout);
        jpMenuDiscoLayout.setHorizontalGroup(
            jpMenuDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuDiscoLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenuDiscoLayout.setVerticalGroup(
            jpMenuDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuDiscoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText(".ControlTec");

        jPanel6.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jpMenuProcessos.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuProcessos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuProcessosMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("PROCESSOS");

        javax.swing.GroupLayout jpMenuProcessosLayout = new javax.swing.GroupLayout(jpMenuProcessos);
        jpMenuProcessos.setLayout(jpMenuProcessosLayout);
        jpMenuProcessosLayout.setHorizontalGroup(
            jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMenuProcessosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpMenuProcessosLayout.setVerticalGroup(
            jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
            .addGroup(jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMenuProcessosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenuCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuDisco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
            .addComponent(jpMenuProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpMenuCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpTela.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Bem Vindo!");

        javax.swing.GroupLayout jpTelaInicioLayout = new javax.swing.GroupLayout(jpTelaInicio);
        jpTelaInicio.setLayout(jpTelaInicioLayout);
        jpTelaInicioLayout.setHorizontalGroup(
            jpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaInicioLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(163, 163, 163))
        );
        jpTelaInicioLayout.setVerticalGroup(
            jpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaInicioLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel14)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jpTelaProcessos.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jpTelaProcessosLayout = new javax.swing.GroupLayout(jpTelaProcessos);
        jpTelaProcessos.setLayout(jpTelaProcessosLayout);
        jpTelaProcessosLayout.setHorizontalGroup(
            jpTelaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jpTelaProcessosLayout.setVerticalGroup(
            jpTelaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jpTelaInformacoes.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpTelaInformacoesLayout = new javax.swing.GroupLayout(jpTelaInformacoes);
        jpTelaInformacoes.setLayout(jpTelaInformacoesLayout);
        jpTelaInformacoesLayout.setHorizontalGroup(
            jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jpTelaInformacoesLayout.setVerticalGroup(
            jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jpTelaRam.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpTelaRamLayout = new javax.swing.GroupLayout(jpTelaRam);
        jpTelaRam.setLayout(jpTelaRamLayout);
        jpTelaRamLayout.setHorizontalGroup(
            jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaRamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTelaRamLayout.setVerticalGroup(
            jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaRamLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jpTelaDisco.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jpTelaDiscoLayout = new javax.swing.GroupLayout(jpTelaDisco);
        jpTelaDisco.setLayout(jpTelaDiscoLayout);
        jpTelaDiscoLayout.setHorizontalGroup(
            jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jpTelaDiscoLayout.setVerticalGroup(
            jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jpTelaCpu.setBackground(new java.awt.Color(255, 255, 255));
        jpTelaCpu.setInheritsPopupMenu(true);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Frequencia Maxima:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Frequencia atual:");

        lblFrequenciaMaxima.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFrequenciaMaxima.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrequenciaMaxima.setText("0.0 GHz");

        lblFrequenciaAtual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFrequenciaAtual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrequenciaAtual.setText("0.0 GHz");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Quantidade de processos:");

        lblQtdProcessos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQtdProcessos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQtdProcessos.setText("0");

        javax.swing.GroupLayout jpGraficoCpuLayout = new javax.swing.GroupLayout(jpGraficoCpu);
        jpGraficoCpu.setLayout(jpGraficoCpuLayout);
        jpGraficoCpuLayout.setHorizontalGroup(
            jpGraficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpGraficoCpuLayout.setVerticalGroup(
            jpGraficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("% de ultilização");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Utilização:");

        lblUsoCpu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsoCpu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsoCpu.setText("0%");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("CPU");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Temperatura:");

        lblTemperaturaCpu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTemperaturaCpu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTemperaturaCpu.setText("0.0°C");

        javax.swing.GroupLayout jpTelaCpuLayout = new javax.swing.GroupLayout(jpTelaCpu);
        jpTelaCpu.setLayout(jpTelaCpuLayout);
        jpTelaCpuLayout.setHorizontalGroup(
            jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGraficoCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpTelaCpuLayout.createSequentialGroup()
                        .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblFrequenciaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(lblUsoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblQtdProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFrequenciaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(52, 52, 52)
                                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(lblTemperaturaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(jpTelaCpuLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(38, 38, 38)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaCpuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(20, 20, 20))
        );
        jpTelaCpuLayout.setVerticalGroup(
            jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGraficoCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrequenciaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrequenciaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperaturaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jpTelaLayout = new javax.swing.GroupLayout(jpTela);
        jpTela.setLayout(jpTelaLayout);
        jpTelaLayout.setHorizontalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTelaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaRam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTelaLayout.setVerticalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTelaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpMenuCpuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuCpuMouseClicked
        trocaCor(jpMenuCpu, jpMenuRam, jpMenuDisco, jpMenuInformacoes, jpMenuProcessos);
        trocaAba(jpTelaCpu, jpTelaRam, jpTelaDisco, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);

    }//GEN-LAST:event_jpMenuCpuMouseClicked

    private void jpMenuRamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuRamMouseClicked
        trocaCor(jpMenuRam, jpMenuDisco, jpMenuCpu, jpMenuInformacoes, jpMenuProcessos);
        trocaAba(jpTelaRam, jpTelaCpu, jpTelaDisco, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);
       
        
    }//GEN-LAST:event_jpMenuRamMouseClicked

    private void jpMenuDiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuDiscoMouseClicked
        trocaCor(jpMenuDisco, jpMenuCpu, jpMenuInformacoes, jpMenuProcessos, jpMenuRam);
        trocaAba(jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);
    }//GEN-LAST:event_jpMenuDiscoMouseClicked

    private void jpMenuInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuInformacoesMouseClicked
        // TODO add your handling code here:
        trocaCor(jpMenuInformacoes, jpMenuDisco, jpMenuCpu, jpMenuProcessos, jpMenuRam);
        trocaAba(jpTelaInformacoes, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaProcessos, jpTelaInicio);
    }//GEN-LAST:event_jpMenuInformacoesMouseClicked

    private void jpMenuProcessosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuProcessosMouseClicked
        // TODO add your handling code here:
        trocaCor(jpMenuProcessos, jpMenuInformacoes, jpMenuDisco, jpMenuCpu, jpMenuRam);
        trocaAba(jpTelaProcessos, jpTelaInformacoes, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInicio);
    }//GEN-LAST:event_jpMenuProcessosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Quando o jframe abre
        trocaAba( jpTelaInicio, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInformacoes, jpTelaProcessos);
        Cpu cpu = new Cpu();
        
       
//        DefaultPieDataset dados = new DefaultPieDataset();


        ActionListener acao = (ActionEvent executar) -> {
            //tela CPU
            usoCpu = cpu.porcetagemDeUso();
            lblFrequenciaAtual.setText(String.format("%.2f GHz", cpu.frenquenciaCpu()));
            lblFrequenciaMaxima.setText(String.format("%.2f GHz", cpu.frequenciaMax()));
            lblQtdProcessos.setText(cpu.quantidadeProcessos().toString());
            lblUsoCpu.setText(String.format("%.2f%%", usoCpu));
            lblTemperaturaCpu.setText(String.format("%.2f°C", cpu.Temperatura()));
            
            dados.addValue(usoCpu,"Uso da cpu",LocalTime.now());
            contador++;
            if(contador.equals(6)){
                dados.removeColumn(0);
                 contador--;
                 
            }
            jpGraficoCpu.add(graficoCpu.GraficoLinha2(dados, jpGraficoCpu.getWidth(), jpGraficoCpu.getHeight()));
            

        };
        Timer tempo = new Timer(1000, acao);

        //iniciar o temporizador
        tempo.start();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }
    public void trocaCor(JPanel troca, JPanel mantem1, JPanel mantem2, JPanel mantem3, JPanel mantem4){
        troca.setBackground(new Color(51,51,255));
        mantem1.setBackground(new Color(204, 204, 255));
        mantem2.setBackground(new Color(204, 204, 255));
        mantem3.setBackground(new Color(204, 204, 255));
        mantem4.setBackground(new Color(204, 204, 255));
    }
    public void trocaAba(JPanel exibe, JPanel oculta1, JPanel oculta2, JPanel oculta3, JPanel oculta4,JPanel oculta5){
        exibe.setVisible(true);
        oculta1.setVisible(false);
        oculta2.setVisible(false);  
        oculta3.setVisible(false);
        oculta4.setVisible(false);
        oculta5.setVisible(false);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel jpGraficoCpu;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpMenuCpu;
    private javax.swing.JPanel jpMenuDisco;
    private javax.swing.JPanel jpMenuInformacoes;
    private javax.swing.JPanel jpMenuProcessos;
    private javax.swing.JPanel jpMenuRam;
    private javax.swing.JPanel jpTela;
    private javax.swing.JPanel jpTelaCpu;
    private javax.swing.JPanel jpTelaDisco;
    private javax.swing.JPanel jpTelaInformacoes;
    private javax.swing.JPanel jpTelaInicio;
    private javax.swing.JPanel jpTelaProcessos;
    private javax.swing.JPanel jpTelaRam;
    private javax.swing.JLabel lblFrequenciaAtual;
    private javax.swing.JLabel lblFrequenciaMaxima;
    private javax.swing.JLabel lblQtdProcessos;
    private javax.swing.JLabel lblTemperaturaCpu;
    private javax.swing.JLabel lblUsoCpu;
    // End of variables declaration//GEN-END:variables
}
